name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v22

      - run: nix develop --command pnpm install --frozen-lockfile

      - name: Lint + Format + Type Check
        run: nix develop --command pnpm check

      - name: Test
        run: nix develop --command pnpm test

      - name: Build
        run: nix develop --command pnpm build

      - name: Publish
        run: nix develop --command npm publish --provenance --access public
